module.exports = {
    URL: {
        ALL_NEWS: "https://inshorts.com/en/read",
        INDIA: "https://inshorts.com/en/read/national",
        BUSINESS: "https://inshorts.com/en/read/business",
        SPORTS: "https://inshorts.com/en/read/sports",
        WORLD: "https://inshorts.com/en/read/world",
        POLITICS: "https://inshorts.com/en/read/politics",
        TECHNOLOGY: "https://inshorts.com/en/read/technology",
        STARTUP: "https://inshorts.com/en/read/startup",
        ENTERTAINMENT: "https://inshorts.com/en/read/entertainment",
        MISCELLANEOUS: "https://inshorts.com/en/read/miscellaneous",
        HATKE: "https://inshorts.com/en/read/hatke",
        SCIENCE: "https://inshorts.com/en/read/science",
        AUTOMOBILE: "https://inshorts.com/en/read/automobile",
    },
    //Responnse
    RESPONSE: {
        SUCCESS: "SUCCESS",
        ERROR: "ERROR",
    },
    //Status Code
    STATUS_CODE: {
        OK: "200",
        INTERNAL_SERVER_ERROR: "500",
        NO_CONTENT: "204",
        NOT_FOUND: "404",
    },
    //Errors
    ERRORS: {
        All_NEWS_ERROR: "All_NEWS_ERROR",
        NATIONAL_NEWS_ERROR: "NATIONAL_NEWS_ERROR",
        BUSINESS_NEWS_ERROR: "BUSINESS_NEWS_ERROR",
        SPORTS_NEWS_ERROR: "SPORTS_NEWS_ERROR",
        WORLD_NEWS_ERROR: "WORLD_NEWS_ERROR",
        POLITICS_NEWS_ERROR: "POLITICS_NEWS_ERROR",
        TECHNOLOGY_NEWS_ERROR: "TECHNOLOGY_NEWS_ERROR",
        STARTUP_NEWS_ERROR: "STARTUP_NEWS_ERROR",
        ENTERTAINMENT_NEWS_ERROR: "ENTERTAINMENT_NEWS_ERROR",
        MISCELLANEOUS_NEWS_ERROR: "MISCELLANEOUS_NEWS_ERROR",
        HATKE_NEWS_ERROR: "HATKE_NEWS_ERROR",
        SCIENCE_NEWS_ERROR: "SCIENCE_NEWS_ERROR",
        AUTOMOBILE_NEWS_ERROR: "AUTOMOBILE_NEWS_ERROR",
    },
    All_NEWS: "All_NEWS",
    NATIONAL_NEWS: "NATIONAL_NEWS",
    BUSINESS_NEWS: "BUSINESS_NEWS",
    SPORTS_NEWS: "SPORTS_NEWS",
    WORLD_NEWS: "WORLD_NEWS",
    POLITICS_NEWS: "POLITICS_NEWS",
    TECHNOLOGY_NEWS: "TECHNOLOGY_NEWS",
    STARTUP_NEWS: "STARTUP_NEWS",
    ENTERTAINMENT_NEWS: "ENTERTAINMENT_NEWS",
    MISCELLANEOUS_NEWS: "MISCELLANEOUS_NEWS",
    HATKE_NEWS: "HATKE_NEWS",
    SCIENCE_NEWS: "SCIENCE_NEWS",
    AUTOMOBILE_NEWS: "AUTOMOBILE_NEWS",

}